function detailPage(row){const config=catalog.modules[row.module];const d=row.data;const sections=config.fields.filter(f=>d[f.key]!==undefined&&d[f.key]!=='');
let chipsHtml=row.module==='materials'?`<div class="chips" style="flex:1">${badge(d.usage_status||'Chưa xác định')}${badge(d.dossier_status||'Chưa đánh giá')}</div>`:config.fields.some(f=>f.key==='dri')?`<div class="chips" style="flex:1">${badge(row.display_status)}<span class="badge">${esc(row.module)}</span><span class="badge">DRI: ${esc(d.dri||'Chưa phân công')}</span></div>`:'';
let actionsHtml=`<button data-route="${row.module}">← Danh sách</button>${can(row.module,'Edit')?'<button id="edit-record" class="primary">Chỉnh sửa</button>':''}${can(row.module,'Delete')?'<button id="archive-record" class="danger">Lưu trữ</button>':''}`;
let html=head(label(row),`${config.title} · Revision ${row.version} · Cập nhật ${timeText(row.updated_at)}`) + `<div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:20px">${chipsHtml}<div class="head-actions" style="display:flex;gap:8px">${actionsHtml}</div></div>`;
if(row.conflicts?.length)html+=`<div class="alert">Mapping FMD / TRM không khớp: ${row.conflicts.map(c=>`${esc(c.test_type)}: FMD ${esc(c.fmd.join(', '))}; TRM ${esc(c.trm.join(', '))}`).join(' · ')}. Cần xác minh báo cáo gốc.</div>`;
if(row.module==='capa'){const stages=[['issue','Issue'],['containment','Containment'],['root_cause','Root Cause'],['corrective','Corrective Action'],['evidence','Evidence'],['verification','Verification'],['closure','Closure']];html+=`<div class="timeline">${stages.map(([k,t])=>`<div class="timeline-step ${(k==='evidence'?row.evidence.length:d[k])?'done':''}"><b>${t}</b><small>${(k==='evidence'?row.evidence.length:d[k])?'Đã ghi nhận':'Chưa ghi nhận'}</small></div>`).join('')}</div>`;}
let infoHtml=`<section class="card" ${row.module==='materials'?'style="margin-bottom:0;border-bottom-left-radius:0;border-bottom-right-radius:0;border-bottom:0"':''}><div class="card-header"><h3>Thông tin hồ sơ</h3></div><div class="card-body"><div class="detail-grid" ${row.module==='materials'?'style="grid-template-columns:1fr 1fr"':''}>${sections.map(f=>`<div class="detail-item"><small>${esc(f.label)}</small><div>${esc(d[f.key])}</div></div>`).join('')}</div>${d._source?`<div class="source" style="margin-top:22px">${sourceText(d._source)}<details><summary>Xem ô nguồn / công thức</summary><pre>${esc(JSON.stringify(d._source,null,2))}</pre></details></div>`:''}${d._sources?`<details><summary>${d._sources.length} dòng nguồn tạo hồ sơ vật liệu</summary>${d._sources.map(s=>`<p class="source">${sourceText(s)}</p>`).join('')}</details>`:''}</div></section>`;
const historyHtml=`<section class="card" ${row.module==='materials'?'style="margin-bottom:0;border-radius:0;border-top:0"':''}><div class="card-header"><h3>Evidence & phiên bản file</h3>${can(row.module,'Upload')?'<label style="margin:0"><input type="file" id="evidence-file" accept=".pdf,.png,.jpg,.jpeg,.xlsx,.docx,.txt" hidden><button id="upload-evidence">↑ Đính kèm file</button></label>':''}</div>${row.evidence.length?`<div class="table-scroll"><table><thead><tr><th>File</th><th>Người upload</th><th>Ngày</th><th>Dung lượng</th><th></th></tr></thead><tbody>${row.evidence.map(e=>`<tr><td title="SHA256: ${e.checksum}">${esc(e.name)}</td><td>${esc(e.uploader)}</td><td>${dateText(e.created_at)}</td><td>${(e.size/1024).toFixed(1)} KB</td><td>${['application/pdf','image/png','image/jpeg'].includes(e.mime)?`<button class="link-button" data-preview="${e.id}">Preview</button> · `:''}<a href="/api/evidence/${e.id}">Tải xuống</a></td></tr>`).join('')}</tbody></table></div>`:empty('Chưa có file evidence','File gốc trong workbook không tự động được coi là evidence đính kèm.')}</section><section class="card" ${row.module==='materials'?'style="border-top-left-radius:0;border-top-right-radius:0;margin-top:0"':''}><div class="card-header"><h3>Lịch sử thay đổi & Audit trail</h3></div><div class="card-body">${row.history.map(h=>`<details><summary>${timeText(h.at)} · ${esc(h.actor)} · ${esc(h.action)}</summary><div class="form-grid"><pre>Trước\n${esc(JSON.stringify(h.before,null,2))}</pre><pre>Sau\n${esc(JSON.stringify(h.after,null,2))}</pre></div></details>`).join('')||'<p class="muted">Chưa có thay đổi sau khi nhập dữ liệu nguồn.</p>'}</div></section>`;
if(row.module==='materials'){
  const related=row.related||[];
  const boms = related.filter(r => r.module === 'bom');
  const bomsHtml = boms.length ? `<section class="card" style="border-top-left-radius:0;border-top-right-radius:0;margin-top:0"><div class="card-header"><h3>Sử dụng trong BOM / Sản phẩm</h3></div>${rowTable(boms)}</section>` : '<section class="card" style="border-top-left-radius:0;border-top-right-radius:0;margin-top:0"><div class="card-body">'+empty('Chưa liên kết với Sản phẩm / BOM nào')+'</div></section>';
  const tabOverview = infoHtml + bomsHtml;
  const tabSuppliers = materialSuppliers(row);
  const compFiles=related.filter(r=>['documents','fmd','cts-1','cts-2','cts-3','reports'].includes(r.module));
  const compType=r=>{if(r.module==='fmd')return'FMD';if(r.module.startsWith('cts'))return r.module.toUpperCase().replace('-','_');const j=JSON.stringify(r.data).toUpperCase();if(j.includes('ROHS'))return'RoHS';if(j.includes('MSDS'))return'MSDS';if(j.includes('SDS'))return'SDS';if(j.includes('HALOGEN'))return'Halogen-Free';if(j.includes('PFO')||j.includes('PFAS'))return'PFAS';if(j.includes('REACH')||j.includes('SVHC'))return'REACH / SVHC';if(j.includes('VOC'))return'VOC';return'Khác';};
  const cTypes=Array.from(new Set(compFiles.map(compType))).sort();
  const compAllowed=can('documents','Upload')||can('reports','Upload');
  const tabCompliance = `<section class="card"><div class="card-header"><div><h3>Hồ sơ tuân thủ & CTS</h3><small class="muted">Mã liên kết: ${esc(row.aliases.join(', '))}</small></div>${compAllowed?'<button class="primary" id="add-comp-report">+ Thêm hồ sơ</button>':''}</div><div class="card-body"><div class="folder-grid">${cTypes.map(type=>{const matches=compFiles.filter(r=>compType(r)===type);return `<div class="folder"><h3>${type}</h3><p>${matches.length} hồ sơ</p>${matches.map(r=>`<p><button class="link-button" data-open="${r.id}">${esc(r.data.report_id||r.data.document_no||r.data.substance||label(r))}</button><br>${badge(r.display_status)} ${r.data.expiry_date?dateText(r.data.expiry_date):''}</p>`).join('')}</div>`;}).join('')}</div>${!cTypes.length?empty('Chưa có hồ sơ tuân thủ'):''}</div></section>`;
  const testFiles = related.filter(r => ['test-plan', 'xrf-plan', 'xrf-iqc', 'xrf-oqc', 'change-control', 'oqc-reports'].includes(r.module) || (r.module==='reports' && compType(r)==='Khác'));
  const tTypes = Array.from(new Set(testFiles.map(r => title(r.module)))).sort();
  let trendHtml = '';
  if (related.some(r => r.module === 'xrf-iqc' || r.module === 'xrf-oqc')) {
    trendHtml = `<div class="alert" style="display:flex;justify-content:space-between;align-items:center;margin-top:20px;margin-bottom:0"><span>Vật liệu này có kết quả đo XRF. Xem biểu đồ đánh giá mức độ rủi ro và xu hướng thay đổi.</span><button class="primary" data-route="xrf-trend">Xem Biểu đồ Trend →</button></div>`;
  }
  const tabTesting = trendHtml + `<section class="card"><div class="card-header"><div><h3>Kế hoạch & Kết quả kiểm nghiệm</h3></div>${can('test-plan','Create')?'<button class="primary" id="add-test-plan">+ Thêm kế hoạch</button>':''}</div><div class="card-body"><div class="folder-grid">${tTypes.map(type=>{const matches=testFiles.filter(r=>title(r.module)===type);return `<div class="folder"><h3>${type}</h3><p>${matches.length} mục</p>${matches.map(r=>`<p><button class="link-button" data-open="${r.id}">${esc(label(r))}</button><br>${badge(r.display_status)}</p>`).join('')}</div>`;}).join('')}</div>${!tTypes.length?empty('Chưa có dữ liệu kiểm nghiệm'):''}</div></section>`;
  html+=`<div class="tabs" role="group" aria-label="Chi tiết vật liệu"><button class="active" data-material-tab="overview" aria-pressed="true">Tổng quan</button><button data-material-tab="suppliers" aria-pressed="false">Nhà cung cấp</button><button data-material-tab="compliance" aria-pressed="false">Hồ sơ tuân thủ</button><button data-material-tab="testing" aria-pressed="false">Kiểm nghiệm</button><button data-material-tab="history" aria-pressed="false">Lịch sử</button></div><div data-material-panel="overview">${tabOverview}</div><div data-material-panel="suppliers" hidden>${tabSuppliers}</div><div data-material-panel="compliance" hidden>${tabCompliance}</div><div data-material-panel="testing" hidden>${tabTesting}</div><div data-material-panel="history" hidden>${historyHtml}</div>`;
}else{
  html+=infoHtml;
  if(row.module==='suppliers')html+=supplierContext(row);
  if(row.module==='bom')html+=`<section class="card"><div class="card-header"><h3>Nguyên vật liệu trong BOM</h3></div>${rowTable(row.materials||[])}</section>`;
  if(row.evaluation)html+=`<section class="card"><div class="card-header"><h3>Đánh giá XRF theo Control Limit</h3>${badge(row.evaluation.status)}</div><div class="table-scroll"><table><thead><tr><th>Chất</th><th>Kết quả ppm</th><th>Giới hạn ppm</th><th>Quy tắc</th><th>Kết luận</th></tr></thead><tbody>${row.evaluation.checks.map(c=>`<tr><td>${esc(c.element)}</td><td>${c.value??'Chưa có'}</td><td>${c.limit??'Chưa khai báo'}</td><td>${esc(c.rule)}</td><td>${badge(c.status)}</td></tr>`).join('')}</tbody></table></div><div class="card-body muted"><small>${esc(row.evaluation.basis)}</small></div></section>`;
  html+=historyHtml;
}
return html;}
